#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-vctrs
Version  : 0.1.0
Release  : 5
URL      : https://cran.r-project.org/src/contrib/vctrs_0.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/vctrs_0.1.0.tar.gz
Summary  : Vector Helpers
Group    : Development/Tools
License  : GPL-3.0
Requires: R-vctrs-lib = %{version}-%{release}
Requires: R-backports
Requires: R-digest
Requires: R-glue
Requires: R-rlang
Requires: R-tibble
Requires: R-zeallot
BuildRequires : R-backports
BuildRequires : R-digest
BuildRequires : R-glue
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : R-zeallot
BuildRequires : buildreq-R

%description
to provide tools for consistent and well-founded type-coercion and 
    size-recycling, and are in turn connected to ideas of type- and 
    size-stability useful for analyzing function interfaces.

%package lib
Summary: lib components for the R-vctrs package.
Group: Libraries

%description lib
lib components for the R-vctrs package.


%prep
%setup -q -c -n vctrs

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562215413

%install
export SOURCE_DATE_EPOCH=1562215413
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library vctrs
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library vctrs
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library vctrs
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc vctrs || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/vctrs/DESCRIPTION
/usr/lib64/R/library/vctrs/INDEX
/usr/lib64/R/library/vctrs/Meta/Rd.rds
/usr/lib64/R/library/vctrs/Meta/features.rds
/usr/lib64/R/library/vctrs/Meta/hsearch.rds
/usr/lib64/R/library/vctrs/Meta/links.rds
/usr/lib64/R/library/vctrs/Meta/nsInfo.rds
/usr/lib64/R/library/vctrs/Meta/package.rds
/usr/lib64/R/library/vctrs/Meta/vignette.rds
/usr/lib64/R/library/vctrs/NAMESPACE
/usr/lib64/R/library/vctrs/R/vctrs
/usr/lib64/R/library/vctrs/R/vctrs.rdb
/usr/lib64/R/library/vctrs/R/vctrs.rdx
/usr/lib64/R/library/vctrs/WORDLIST
/usr/lib64/R/library/vctrs/doc/index.html
/usr/lib64/R/library/vctrs/doc/s3-vector.R
/usr/lib64/R/library/vctrs/doc/s3-vector.Rmd
/usr/lib64/R/library/vctrs/doc/s3-vector.html
/usr/lib64/R/library/vctrs/doc/stability.R
/usr/lib64/R/library/vctrs/doc/stability.Rmd
/usr/lib64/R/library/vctrs/doc/stability.html
/usr/lib64/R/library/vctrs/doc/type-size.R
/usr/lib64/R/library/vctrs/doc/type-size.Rmd
/usr/lib64/R/library/vctrs/doc/type-size.html
/usr/lib64/R/library/vctrs/help/AnIndex
/usr/lib64/R/library/vctrs/help/aliases.rds
/usr/lib64/R/library/vctrs/help/figures/cast.png
/usr/lib64/R/library/vctrs/help/figures/coerce.png
/usr/lib64/R/library/vctrs/help/figures/combined.png
/usr/lib64/R/library/vctrs/help/figures/logo.png
/usr/lib64/R/library/vctrs/help/figures/sizes-recycling.png
/usr/lib64/R/library/vctrs/help/paths.rds
/usr/lib64/R/library/vctrs/help/vctrs.rdb
/usr/lib64/R/library/vctrs/help/vctrs.rdx
/usr/lib64/R/library/vctrs/html/00Index.html
/usr/lib64/R/library/vctrs/html/R.css
/usr/lib64/R/library/vctrs/tests/testthat.R
/usr/lib64/R/library/vctrs/tests/testthat/helper-expectations.R
/usr/lib64/R/library/vctrs/tests/testthat/test-arith.R
/usr/lib64/R/library/vctrs/tests/testthat/test-bind.R
/usr/lib64/R/library/vctrs/tests/testthat/test-c.R
/usr/lib64/R/library/vctrs/tests/testthat/test-cast-list.R
/usr/lib64/R/library/vctrs/tests/testthat/test-cast.R
/usr/lib64/R/library/vctrs/tests/testthat/test-compare.R
/usr/lib64/R/library/vctrs/tests/testthat/test-data.R
/usr/lib64/R/library/vctrs/tests/testthat/test-dictionary.R
/usr/lib64/R/library/vctrs/tests/testthat/test-dim.R
/usr/lib64/R/library/vctrs/tests/testthat/test-empty.R
/usr/lib64/R/library/vctrs/tests/testthat/test-equal.R
/usr/lib64/R/library/vctrs/tests/testthat/test-fields.R
/usr/lib64/R/library/vctrs/tests/testthat/test-hash-hash.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-hash.R
/usr/lib64/R/library/vctrs/tests/testthat/test-list_of-print.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-list_of-str.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-list_of-type.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-list_of.R
/usr/lib64/R/library/vctrs/tests/testthat/test-partial-frame-print.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-partial-frame.R
/usr/lib64/R/library/vctrs/tests/testthat/test-print-str-attr.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-print-str-mtcars.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-print-str.R
/usr/lib64/R/library/vctrs/tests/testthat/test-prototype.R
/usr/lib64/R/library/vctrs/tests/testthat/test-ptype-abbr-full.R
/usr/lib64/R/library/vctrs/tests/testthat/test-rcrd-format.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-record.R
/usr/lib64/R/library/vctrs/tests/testthat/test-recycle.R
/usr/lib64/R/library/vctrs/tests/testthat/test-sclr.R
/usr/lib64/R/library/vctrs/tests/testthat/test-shape-print.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-shape.R
/usr/lib64/R/library/vctrs/tests/testthat/test-size.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type-data-frame-embedded.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-type-data-frame.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type-data-frame.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-type-date-time.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type-date-time.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-type-factor.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type-factor.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-type-tibble.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type2.R
/usr/lib64/R/library/vctrs/tests/testthat/test-type2.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-unspecified.R
/usr/lib64/R/library/vctrs/tests/testthat/test-unspecified.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-utils.R
/usr/lib64/R/library/vctrs/tests/testthat/test-vctr-print-names.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-vctr-print.txt
/usr/lib64/R/library/vctrs/tests/testthat/test-vctr.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/vctrs/libs/vctrs.so
